const mongoose=require("mongoose")

const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true,
        lowercase:true
    },
    age:{
        type:Number,
        required:true
    },
    gender:{
        type:String,
        required:true
    },
    degree:{
        type:String,
        required:true,
        trim:true
    },
    medicalIssue:{
        type:String,
        required:true
    },
    interested:{
        type:[String],
        default:[]
    },
    contactDetails:{
        area:{
            type:String,
            required:true,
            trim:true,
            lowercase:true
        },
        district:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        phoneNumber:{
            type:String,
            required:true
        }
    },
    email:{
        type:String,
        required:true,
        trim:true,
        lowercase:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    }},{timestamps:true})

const Volunteer=mongoose.model("Volunteer",userSchema);
module.exports=Volunteer;